### ISSUE TITLE
Detection results differ between JVM and Go edition of Lingua

### ISSUE THREAD

**Issue by hwdlei** [pemistahl/lingua-go#14] opened 2022-09-27 13:18 UTC
For some text samples, Lingua-go detected the wrong language, but Lingua's results were correct.

Examples:

texts | lingua-go|lingua
-- | -- | --
  Chắc tại có +18:)?| Malay  |  VIETNAMESE

**Comment by pemistahl** [comment] 2022-09-28 08:23
Thanks @hwdlei for letting me know. I'm going to work on lingua-go now anyway, so I will investigate if and how the detection result differ between the JVM and the Go version.

**Comment by pemistahl** [comment] 2022-11-08 20:56
Hi @hwdlei, I was finally able to find the cause of the problem. So this will be fixed in the next release 1.1.0.

**Closed by pemistahl** 2022-11-08 20:56 UTC
Labels: bug
